_target_: erl_lib.agent.module.critic.critic.EnsembleCriticNetwork
dim_obs: ${agent.dim_obs}
dim_act: ${agent.dim_act}
dim_hidden: 512
num_hidden: 2
num_members: 2
norm_eps: 0.0
bound_factor: 1.0
bounded_prediction: False