defaults:
  - /agent/sac@_here_

normalize_po_input: True
# Actor
actor_reduction: mean
# Critic
bounded_critic: True
scaled_critic: True
critic:
  dropout_rate: 1e-3
  norm_eps: 1e-5
  num_members: 5
