_target_: erl_lib.agent.model_based.modules.gaussian_mlp.GaussianMLP
device: ${common.device}
num_members: 8
dim_hidden: 256
layer_norm: 1.0
drop_rate_base: 1e-2
noise_wd: 1e-2
lb_std: 1e-3
weight_decay_base: 1e-3
weight_decay_ratios:
  - 0.25
  - 0.5
  - 0.75
  - 1.0
priors_on_function_values: False
prediction_strategy: ts_1
mse_score: False
sum_over_data: True
training_loss_fn: nll
normalized_target: True
residual: False
uncertainty_bonus: False